# Generated by Django 5.2.3 on 2025-07-07 22:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('document_type', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Word'), ('ppt', 'PowerPoint'), ('xls', 'Excel'), ('txt', 'Text'), ('img', 'Image'), ('aud', 'Audio'), ('vid', 'Video'), ('arc', 'Archive'), ('oth', 'Other')], max_length=3)),
                ('storage_path', models.CharField(max_length=512)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_time'],
            },
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner', 'upload_time'], name='api_documen_owner_i_f4ffc5_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['file_name'], name='api_documen_file_na_a8a704_idx'),
        ),
    ]
