# Generated by Django 5.2.5 on 2025-09-08 01:19

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_document_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
