# Generated by Django 5.2.3 on 2025-07-14 09:54

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_document_delete_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
