# Generated by Django 5.2.3 on 2025-07-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_document_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
