# Generated by Django 5.2.5 on 2025-09-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_document_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
